// Generated by CoffeeScript 1.6.3
(function() {
  var db, model, util;

  db = require('mysqlp');

  util = require('./lib/util');

  model = require('./lib/model');

  module.exports.config = function(config) {
    db.config(config.databases);
    this.models = util.loadModules(config.modelsPath, [], function(loadedModule) {
      var obj;
      console.log('loading');
      obj = Object.create(model(db));
      if (typeof loadedModule === 'function') {
        loadedModule(obj);
        return obj;
      }
    });
    return this.models;
  };

}).call(this);
