// Generated by CoffeeScript 1.6.3
(function() {
  var fs, path,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  fs = require('fs');

  path = require('path');

  module.exports.loadModules = function(modulesPath, ignore, callback) {
    var extension, fileName, loadedModule, modules, name, _i, _len, _ref;
    if (ignore == null) {
      ignore = [];
    }
    if (callback == null) {
      callback = false;
    }
    modules = {};
    _ref = fs.readdirSync(modulesPath);
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      fileName = _ref[_i];
      extension = path.extname(fileName);
      name = path.basename(fileName, extension);
      if (/^[a-zA-Z]+$/.test(name) && __indexOf.call(ignore, name) < 0) {
        loadedModule = require(path.join(modulesPath, name));
        modules[name] = callback ? callback(loadedModule) : loadedModule;
      }
    }
    return modules;
  };

}).call(this);
